-- DDL CRIACAO DE TABELA PARA EXERCICIOS

CREATE TABLE FUNCIONARIOS
(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
SALARIO DECIMAL(10,2),
SETOR VARCHAR(30),
PRIMARY KEY(ID)
);

-- DML SELECT

SELECT * FROM funcionarios

-- EXEMPLO SELECT

SELECT NOME, SETOR AS DEPARTAMENTO FROM funcionarios

-- DML INSERT

INSERT INTO funcionarios (NOME, SALARIO, SETOR) VALUES
("JOAO", 1000, ""), 
("JOSE", 2000, ""), 
("ALEXANDRE", 3000, "");

INSERT INTO funcionarios (NOME, SALARIO) VALUES ("PEDRO", 1000);
INSERT INTO funcionarios (NOME, SALARIO) VALUES ("CLEITON", 1080);

-- DML UPDATE

UPDATE funcionarios SET SALARIO = 1500
WHERE ID = 1;

-- AUMENTO DE SALARIO PARA 50% SOBRE ATUAL

UPDATE funcionarios SET SALARIO = SALARIO * 1.5
WHERE ID = 2;

-- EXEMPLO UPDATE COM MAIS DE UM CAMPO

UPDATE funcionarios SET SALARIO = SALARIO * 1.5, SETOR = "TI"
WHERE ID <> 1;

-- DML DELETE 

DELETE FROM funcionarios
WHERE ID = 1;

