-- DDL CRIACAO DE TABELA PARA EXERCICIOS

CREATE TABLE FUNCIONARIOS
(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
SALARIO DECIMAL(10,2),
SETOR VARCHAR(30),
PRIMARY KEY(ID)
);

-- DML SELECT

SELECT * FROM funcionarios

-- EXEMPLO SELECT

SELECT NOME, SETOR AS DEPARTAMENTO FROM funcionarios

-- DML INSERT

INSERT INTO funcionarios (NOME, SALARIO, SETOR) VALUES
("JOAO", 1000, ""), 
("JOSE", 2000, ""), 
("ALEXANDRE", 3000, "");

INSERT INTO funcionarios (NOME, SALARIO) VALUES ("PEDRO", 1000);
INSERT INTO funcionarios (NOME, SALARIO) VALUES ("CLEITON", 1080);

-- DML UPDATE

UPDATE funcionarios SET SALARIO = 1500
WHERE ID = 1;

-- AUMENTO DE SALARIO PARA 50% SOBRE ATUAL

UPDATE funcionarios SET SALARIO = SALARIO * 1.5
WHERE ID = 2;

-- EXEMPLO UPDATE COM MAIS DE UM CAMPO

UPDATE funcionarios SET SALARIO = SALARIO * 1.5, SETOR = "TI"
WHERE ID <> 1;

-- DML DELETE 

DELETE FROM funcionarios
WHERE ID = 1;


-- CRIANDO OUTRA TABELA

CREATE TABLE funcionario
(
	matricula INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome      VARCHAR(50) NOT NULL,
	sobrenome VARCHAR(50) NOT NULL,
	endereco  VARCHAR(50),
	cidade    VARCHAR(50),
	pais      VARCHAR(25),
	data_nasc DATETIME	
);

-- USANDO CHAVE ESTRANGEIRA

CREATE TABLE salario
(
	matricula INT NOT NULL,
	salario DECIMAL(10,2) NOT NULL,
	FOREIGN KEY(matricula) REFERENCES funcionario(matricula)
);

-- DDL CRIAÇÃO DE TABELA COM CHAVE PRIMARIA

CREATE TABLE audit_salario
(
	transacao  INT NOT NULL AUTO_INCREMENT,
	matricula  INT NOT NULL,
	data_trans DATETIME NOT NULL,
	sal_antigo DECIMAL(10,2),
	sal_novo   DECIMAL(10,2),
	Usuario    VARCHAR(20) NOT NULL,
	PRIMARY KEY (transacao),
	FOREIGN KEY(matricula) REFERENCES funcionario(matricula)
);

-- DDL CRIACAO DE INDEX

CREATE INDEX ix_func1 ON funcionario(data_nasc);

CREATE INDEX ix_func ON funcionario(cidade, pais);

-- ADICIONANDO NOVO CAMPO NA TABELA

ALTER TABLE funcionario ADD genero CHAR(1);

-- RENOMEANDO CAMPO/COLUNA DA TABELA

ALTER TABLE funcionario CHANGE genero sexo CHAR(1);

-- RETORNANDO SITUACAO ANTERIOR

ALTER TABLE funcionario CHANGE sexo genero CHAR(1);

-- RENOMEANDO TABELA

RENAME TABLE funcionario TO pessoa;

-- RETORNANDO A SITUACAO ANTERIOR

RENAME TABLE pessoa TO funcionario;


SELECT * FROM funcionario

-- DDL PARA ADICIONAR COLUNA NO TAB SENSO

ALTER TABLE senso ADD ID INT;

-- DDL PARA ADICIONAR CHAVE PRIMARIA NA TAB SENSO AUTO_INCREMENT

ALTER TABLE senso MODIFY COLUMN ID INT PRIMARY KEY AUTO_INCREMENT;

-- ALTERANTO TIPO DE COLUNA

ALTER TABLE funcionario MODIFY COLUMN endereco VARCHAR(30);

-- EXCLUINDO CAMPO DE UMA COLUNA

ALTER TABLE funcionario DROP COLUMN genero;

-- ALTERAR ENGINE DA TABELA

ALTER TABLE senso
ENGINE = MYISAM;

-- CRIAR DATABASE

CREATE DATABASE TESTE;

-- DELETAR DATABASE

DROP DATABASE TESTE;

-- DELETAR TABELA

DROP TABLE salario;

-- CRIANDO VIEW

CREATE VIEW v_funcionario AS SELECT * FROM funcionarios;

-- MODIFICANDO VIEW

ALTER VIEW v_funcionario AS SELECT ID, NOME FROM funcionarios;

-- EXCLUINDO VIEW

DROP VIEW v_funcionario;

SELECT * FROM v_funcionario

SELECT * FROM funcionario;