-- DDL CRIACAO DE TABELA PARA EXERCICIOS

CREATE TABLE FUNCIONARIOS
(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
SALARIO DECIMAL(10,2),
SETOR VARCHAR(30),
PRIMARY KEY(ID)
);

-- DML SELECT

SELECT * FROM FUNCIONARIOS